"""
Service that integrates the agent system with the main application.
"""

from typing import Dict, Any, List
from langfuse import Langfuse
import logging
import os

from app.agents.workflow_graph import TravelWorkflowGraph
from app.agents.travel_agent import TravelAgent

logger = logging.getLogger(__name__)

class AgentService:
    """
    Service that integrates the agent system with the existing application.
    """
    
    def __init__(self):
        # Initialize Langfuse for observability
        self.langfuse = self._initialize_langfuse()
        
        # Initialize agents
        self.workflow_graph = TravelWorkflowGraph()
        self.travel_agent = TravelAgent(langfuse_client=self.langfuse)
        
        logger.info("AgentService initialized correctly")
    
    def _initialize_langfuse(self) -> Langfuse:
        """
        Initializes Langfuse for observability.
        """
        try:
            # Get Langfuse credentials from environment variables
            langfuse_public_key = os.getenv("LANGFUSE_PUBLIC_KEY")
            langfuse_secret_key = os.getenv("LANGFUSE_SECRET_KEY")
            langfuse_host = os.getenv("LANGFUSE_HOST", "https://cloud.langfuse.com")
            
            if langfuse_public_key and langfuse_secret_key:
                return Langfuse(
                    public_key=langfuse_public_key,
                    secret_key=langfuse_secret_key,
                    host=langfuse_host
                )
            else:
                logger.warning("Langfuse not configured. Continuing without observability.")
                return None
                
        except Exception as e:
            logger.warning(f"Could not initialize Langfuse: {e}")
            return None
    
    async def process_message_with_agents(self, message: str, user_id: str, 
                                        use_workflow: bool = True) -> Dict[str, Any]:
        """
        Processes a message using the agent system.
        
        Args:
            message: User message
            user_id: User ID
            use_workflow: Whether to use the workflow graph or simple agent
        """
        try:
            logger.info(f"Processing message with agents for user {user_id}")
            
            if use_workflow:
                # Use the workflow graph
                response = await self.workflow_graph.process_request(message)
            else:
                # Use the simple agent
                response = await self.travel_agent.process_request(message, user_id)
            
            # Add tracking information
            response["agent_system"] = "langchain_langgraph"
            response["workflow_used"] = use_workflow
            
            logger.info(f"Response generated by agents: {response.get('intention', 'unknown')}")
            
            return response
            
        except Exception as e:
            logger.error(f"Error processing message with agents: {e}")
            return {
                "message": f"Sorry, there was an error processing your request: {str(e)}",
                "is_user": False,
                "intention": "error",
                "agent_system": "langchain_langgraph",
                "error": str(e)
            }
    
    async def create_itinerary_with_agents(self, country: str, cities: List[str] = None,
                                         preferences: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Creates an itinerary using the agent system.
        """
        try:
            logger.info(f"Creating itinerary with agents for {country}")
            
            # Build message for the agent
            message = f"I want to create an itinerary for {country}"
            if cities:
                message += f" visiting {', '.join(cities)}"
            if preferences:
                message += f" with preferences: {preferences}"
            
            # Process with agents
            response = await self.process_message_with_agents(message, "itinerary_creation")
            
            # Add additional information
            response["country"] = country
            response["cities_requested"] = cities
            response["preferences"] = preferences
            
            return response
            
        except Exception as e:
            logger.error(f"Error creating itinerary with agents: {e}")
            return {
                "message": f"Error creating itinerary: {str(e)}",
                "is_user": False,
                "intention": "error",
                "country": country,
                "error": str(e)
            }
    
    async def optimize_route_with_agents(self, cities: List[Dict[str, Any]], 
                                       optimization_type: str = "tsp") -> Dict[str, Any]:
        """
        Optimizes a route using the routing agent.
        """
        try:
            from app.agents.routing_agent import RoutingAgent
            
            routing_agent = RoutingAgent()
            
            if optimization_type == "tsp":
                route = routing_agent.calculate_route(cities)
            elif optimization_type == "time":
                route = routing_agent.optimize_for_time(cities)
            else:
                route = routing_agent.calculate_route(cities)
            
            return {
                "route": route,
                "optimization_type": optimization_type,
                "cities_count": len(cities),
                "total_distance": route.get("total_distance", 0),
                "estimated_time": route.get("estimated_time", 0)
            }
            
        except Exception as e:
            logger.error(f"Error optimizing route: {e}")
            return {
                "error": str(e),
                "route": None,
                "optimization_type": optimization_type
            }
    
    async def search_cities_with_agents(self, country: str) -> Dict[str, Any]:
        """
        Searches for cities using the database agent.
        """
        try:
            from app.agents.database_agent import DatabaseAgent
            
            db_agent = DatabaseAgent()
            cities = await db_agent.search_cities_by_country(country)
            
            return {
                "cities": cities,
                "country": country,
                "cities_count": len(cities),
                "search_successful": True
            }
            
        except Exception as e:
            logger.error(f"Error searching cities: {e}")
            return {
                "cities": [],
                "country": country,
                "cities_count": 0,
                "search_successful": False,
                "error": str(e)
            }
    
    def get_agent_status(self) -> Dict[str, Any]:
        """
        Gets the status of the agents.
        """
        return {
            "langfuse_configured": self.langfuse is not None,
            "workflow_graph_ready": hasattr(self, 'workflow_graph'),
            "travel_agent_ready": hasattr(self, 'travel_agent'),
            "agent_system": "langchain_langgraph"
        }
    
    async def test_agent_connection(self) -> Dict[str, Any]:
        """
        Tests the agent connections.
        """
        try:
            # Test city search
            cities_result = await self.search_cities_with_agents("Thailand")
            
            # Test route optimization
            if cities_result.get("cities"):
                route_result = await self.optimize_route_with_agents(cities_result["cities"][:3])
            else:
                route_result = {"error": "No cities to test"}
            
            return {
                "database_agent": cities_result.get("search_successful", False),
                "routing_agent": "error" not in route_result,
                "langfuse": self.langfuse is not None,
                "overall_status": "healthy" if cities_result.get("search_successful") else "partial"
            }
            
        except Exception as e:
            logger.error(f"Error in connection test: {e}")
            return {
                "database_agent": False,
                "routing_agent": False,
                "langfuse": self.langfuse is not None,
                "overall_status": "error",
                "error": str(e)
            }

# Global instance of the agent service
agent_service = AgentService() 