name: Publish Frontend (Mock) to gh-pages branch

on:
  push:
    branches: [ demo-mock ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build (Mock)
        working-directory: frontend
        env:
          REACT_APP_MOCK: "true"
          CI: "false"
          DISABLE_ESLINT_PLUGIN: "true"
        run: npm run build

      - name: Add SPA fallback (404)
        run: cp frontend/build/index.html frontend/build/404.html

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          publish_branch: gh-pages
          commit_message: Deploy mock build to gh-pages


