name: Deploy Frontend (Mock) to GitHub Pages

on:
  push:
    branches: [ demo-mock ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build (Mock)
        working-directory: frontend
        env:
          REACT_APP_MOCK: "true"
          CI: "false"
          DISABLE_ESLINT_PLUGIN: "true"
        run: npm run build

      - name: SPA fallback (404 -> index.html)
        run: cp frontend/build/index.html frontend/build/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4


